#ifndef ErrorCode_H
#define ErrorCode_H

typedef enum{ERR_NO_ERROR,
			 ERR_INCOMPLETE_NUMBER, 
			 ERR_NOT_NUMBER_TOKEN,
			 ERR_STACK_EMPTY,
			 ERR_STACK_FULL,
       ERR_UNKNOWN_OPERATOR,
       ERR_NOT_PREFIX_OPERATOR,
       ERR_IDENTIFIER_NOT_SUPPORT,
       ERR_EXPECTING_NUMBER,
       ERR_NO_OPEN_BRACKET,
       ERR_NO_CLOSING_BRACKET,
       ERR_UNBALANCE_BRACKET,
       ERR_NOT_EXPECTING_NUMBER} ErrorCode;

#endif // ErrorCode_H
